name: Run Docker integration tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Set permissions for log directory
      run: |
        mkdir -p /home/runner/.letta/logs
        sudo chown -R $USER:$USER /home/runner/.letta/logs
        chmod -R 755 /home/runner/.letta/logs

    - name: Start PostgreSQL via Docker
      run: |
        docker compose -f dev-compose.yaml up -d
        echo "Waiting for PostgreSQL to be ready..."
        sleep 5

    - name: Install Poetry and Dependencies
      run: |
        pipx install poetry==2.1.3
        poetry install -E dev -E postgres

    - name: Start Letta Server in Background
      env:
        LETTA_PG_DB:   letta
        LETTA_PG_USER: letta
        LETTA_PG_PASSWORD: letta
        LETTA_PG_PORT: 8888
        LETTA_PG_HOST: localhost
        LETTA_SERVER_PASS: test_server_token
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        poetry run letta server --port 8283 &
        echo "Letta server started in background"

    - name: Wait for service
      run: bash scripts/wait_for_service.sh http://localhost:8283 -- echo "Service is ready"

    - name: Run tests with pytest
      env:
        LETTA_PG_DB:   letta
        LETTA_PG_USER: letta
        LETTA_PG_PASSWORD: letta
        LETTA_PG_PORT: 8888
        LETTA_PG_HOST: localhost
        LETTA_SERVER_PASS: test_server_token
        LETTA_SERVER_URL: http://localhost:8283
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        PYTHONPATH: ${{ github.workspace }}:${{ env.PYTHONPATH }}
      run: |
        poetry run pytest -s tests/test_client.py
#        poetry run pytest -s tests/test_client_legacy.py

    - name: Print docker logs if tests fail
      if: failure()
      run: |
        echo "Printing Docker Logs..."
        docker compose -f dev-compose.yaml logs
